### ISSUE TITLE
[bug-report] bot show response to wrong UUID

### ISSUE THREAD

**Issue by AliM1988** [diditra/x-ui#10]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I have a client with UUID : ef3dd210-8954-11ed-a77f-1495dbb28315
When I enter /usage ef3dd210-8954-11ed-a77f-1495dbb2831   (the last character is missing)  it show below response!

💡 Active: true
📧 Name: 
🔄 Total: 0.00B / unlimited
📅 Expires on: unlimited

### Version of x-ui

1.1.4

### x-ui log or xray log

...

**Comment by diditra** [comment]
Should be fixed in v1.1.5. Can you confirm?

**Comment by AliM1988** [comment]
Yes, It's fixed.
